#!/bin/bash
# Complete deployment verification and fix script

echo "=== RDS Account Verification ==="
echo "Run these commands in RDS account CloudShell:"
echo ""
echo "cd rds"
echo ""
echo "# Test if data exists"
echo "aws lambda invoke --function-name rds-proxy-lambda --cli-binary-format raw-in-base64-out --payload '{\"body\":\"{\\\"transaction_id\\\":\\\"10234567\\\"}\"}' response.json && cat response.json"
echo ""
echo "# If response shows null, load data:"
echo "aws lambda invoke --function-name rds-proxy-lambda --cli-binary-format raw-in-base64-out --payload '{\"body\":\"{\\\"sql\\\":\\\"INSERT INTO transactions (transaction_id, description) VALUES (10234567, '\\''Online purchase at Amazon'\\''), (20456789, '\\''Gas station payment'\\''), (30678901, '\\''Grocery store checkout'\\''), (40891234, '\\''Restaurant dinner bill'\\''), (50123456, '\\''Monthly subscription fee'\\''), (60345678, '\\''ATM cash withdrawal'\\''), (70567890, '\\''Electric utility payment'\\''), (80789012, '\\''Coffee shop purchase'\\''), (90901234, '\\''Movie ticket booking'\\''), (11223344, '\\''Pharmacy medication buy'\\''), (22334455, '\\''Hotel accommodation charge'\\''), (33445566, '\\''Airline ticket purchase'\\''), (44556677, '\\''Car rental service'\\''), (55667788, '\\''Mobile phone bill payment'\\''), (66778899, '\\''Internet service charge'\\''), (77889900, '\\''Gym membership renewal'\\''), (88990011, '\\''Book store purchase'\\''), (99001122, '\\''Pet supplies shopping'\\''), (12345678, '\\''Home insurance premium'\\''), (23456789, '\\''Streaming service fee'\\'')\\\"}'}' response.json && cat response.json"
echo ""
echo "=== Lambda Account Verification ==="
echo "Run these commands in Lambda account CloudShell:"
echo ""
echo "cd lambda"
echo ""
echo "# Check VPC Lattice endpoint"
echo "aws lambda get-function-configuration --function-name transaction-rds-reader --query 'Environment.Variables.VPC_LATTICE_ENDPOINT'"
echo ""
echo "# Update HTML with API endpoint"
echo "API_ENDPOINT=\$(terraform output -raw api_endpoint)"
echo "sed \"s|API_ENDPOINT_PLACEHOLDER|\$API_ENDPOINT|g\" query.html > query_updated.html"
echo "BUCKET_NAME=\$(terraform output -raw website_url | cut -d'/' -f3 | cut -d'.' -f1)"
echo "aws s3 cp query_updated.html s3://\$BUCKET_NAME/index.html --content-type text/html"
echo "echo \"Website: \$(terraform output -raw website_url)\""
